name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: build
        shell: bash
        run: |
          pwd
          ./vcpkg/vcpkg-bootstrap.sh
          ./vcpkg/vcpkg install abseil:x64-linux
      - name: collect logs
        if: always()
        run: |
          shopt -s globstar
          tar caf logs.tar --ignore-failed-read vcpkg/buildtrees/**/*.log
      - name: Upload Logs
        uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: logs
          path: logs.tar
